# Generated by Django 2.1.1 on 2019-07-09 03:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(help_text='店铺名称', max_length=50, verbose_name='名称')),
                ('detail', tinymce.models.HTMLField(help_text='门店简介', verbose_name='门店简介')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('address', models.CharField(help_text='地址', max_length=100, verbose_name='地址')),
                ('image', models.CharField(help_text='门店图片', max_length=1000, verbose_name='门店图片')),
                ('tip', models.CharField(help_text='tip', max_length=100, verbose_name='tip')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'db_table': 'df_store',
            },
        ),
    ]
