# Generated by Django 2.1.1 on 2019-07-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190715_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.CharField(help_text='图片', max_length=1000, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '门店图片',
                'verbose_name_plural': '门店图片',
                'db_table': 'df_store_image',
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(help_text='门店id', on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='门店'),
        ),
    ]
