# Generated by Django 2.1.1 on 2019-07-09 03:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.CharField(help_text='图片', max_length=1000, verbose_name='图片路径')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
            ],
            options={
                'verbose_name': '首页轮播商品',
                'verbose_name_plural': '首页轮播商品',
                'db_table': 'df_index_banner',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(help_text='视频名称', max_length=50, verbose_name='名称')),
                ('desc', models.CharField(help_text='商品描述', max_length=256, verbose_name='商品描述')),
                ('detail', tinymce.models.HTMLField(help_text='商品简介', verbose_name='商品简介')),
                ('url', models.ImageField(help_text='视频url', upload_to='video', verbose_name='视频')),
                ('price', models.DecimalField(decimal_places=2, help_text='视频价格', max_digits=10, verbose_name='视频价格')),
                ('number', models.IntegerField(verbose_name='人数')),
                ('status', models.SmallIntegerField(choices=[(0, '免费'), (1, '付费')], default=0, verbose_name='视频状态')),
                ('image', models.CharField(help_text='视频图片', max_length=1000, verbose_name='视频图片')),
                ('is_recommend', models.SmallIntegerField(choices=[(0, '免费'), (1, '付费')], default=0, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'df_video',
            },
        ),
        migrations.AddField(
            model_name='indexgoodsbanner',
            name='video',
            field=models.ForeignKey(help_text='视频id', on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name='视频'),
        ),
    ]
