# Generated by Django 2.1.1 on 2019-07-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_recommend',
            field=models.SmallIntegerField(choices=[(0, '是'), (1, '否')], default=0, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='video',
            name='number',
            field=models.IntegerField(default=0, verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='视频价格', max_digits=10, null=True, verbose_name='视频价格'),
        ),
    ]
