# Generated by Django 2.1.1 on 2019-07-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190710_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(help_text='视频url', upload_to='video', verbose_name='视频'),
        ),
    ]
