# Generated by Django 2.1.1 on 2019-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190710_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='视频价格', max_digits=10, verbose_name='视频价格'),
        ),
    ]
