# Generated by Django 2.1.1 on 2019-07-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20190712_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexgoodsbanner',
            name='index',
        ),
    ]
