# Generated by Django 2.1.1 on 2019-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20190719_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexgoodsbanner',
            options={'verbose_name': '轮播商品', 'verbose_name_plural': '轮播商品'},
        ),
        migrations.AddField(
            model_name='indexgoodsbanner',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, help_text='是否首页轮播', verbose_name='是否首页轮播'),
        ),
    ]
