# Generated by Django 2.1.1 on 2019-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20190723_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='视频url', verbose_name='视频'),
        ),
    ]
