# Generated by Django 2.1.1 on 2019-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20190723_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='try_see',
            field=models.URLField(blank=True, help_text='试看视频url', null=True, verbose_name='试看视频'),
        ),
    ]
