# Generated by Django 2.1.1 on 2019-07-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_try_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='standard_para',
            field=models.CharField(blank=True, help_text='规格参数', max_length=1000, null=True, verbose_name='规格参数'),
        ),
    ]
