# Generated by Django 2.1.1 on 2019-07-19 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(help_text='市', on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='users.Area', verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(help_text='区', on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='users.Area', verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(help_text='省', on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='users.Area', verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='名称', max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='上级行政区划', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='users.Area', verbose_name='上级行政区划'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='生日', null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(help_text='手机号', max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='昵称', max_length=100, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, help_text='openid', max_length=64, null=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, help_text='性别', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
