# Generated by Django 2.1.1 on 2019-07-12 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20190709_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
            preserve_default=False,
        ),
    ]
