# Generated by Django 2.1.1 on 2019-07-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordergoods_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已取消')], default=1, verbose_name='订单状态'),
        ),
    ]
