# Generated by Django 2.1.1 on 2019-07-19 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordergoods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已取消')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='user',
            field=models.ForeignKey(help_text='下单用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='video',
            field=models.ForeignKey(help_text='订单商品', on_delete=django.db.models.deletion.PROTECT, to='videos.Video', verbose_name='订单商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(help_text='订单号', max_length=64, primary_key=True, serialize=False, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已取消')], default=1, help_text='订单状态', verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='商品总金额', max_digits=10, verbose_name='商品总金额'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_count',
            field=models.IntegerField(default=1, help_text='商品总数', verbose_name='商品总数'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(help_text='下单用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
    ]
