# Generated by Django 2.1.1 on 2019-07-29 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190726_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='video',
            field=models.ForeignKey(help_text='订单商品', on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video', verbose_name='订单商品'),
        ),
    ]
