# Generated by Django 2.1.1 on 2019-07-29 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190729_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='user',
            field=models.ForeignKey(help_text='下单用户', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='video',
            field=models.ForeignKey(help_text='订单商品', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video', verbose_name='订单商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(help_text='下单用户', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
    ]
