# Generated by Django 2.1.1 on 2019-07-29 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190729_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='video',
            field=models.ForeignKey(help_text='订单商品', null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name='订单商品'),
        ),
    ]
