# Generated by Django 2.1.1 on 2019-07-09 03:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(help_text='品牌名称', max_length=50, verbose_name='品牌')),
                ('detail', tinymce.models.HTMLField(help_text='品牌描述', verbose_name='品牌描述')),
                ('image', models.CharField(help_text='图片', max_length=1000, verbose_name='图片')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'df_brand',
            },
        ),
    ]
